### PR TITLE
--screen-saver

### LINKED ISSUE #4: Would love an autosolve
Would be great to use this as a TUI screensaver if you could add an option for it to solve the maze. Similar to the widely used xscreensaver maze module (https://jwz.org/xscreensaver/screenshots/)

### PR DESCRIPTION
**Pull request by Canop**
With this option, mazter doesn't need a player.

Run `mazter --screen-saver`

Fix #4

### CODE REVIEW

**Comment by tachijuan** [comment]
I'm a complete newb when it comes to the Rust ecosystem.  I did a `cargo install mazter --force` to recompile but that seems to still pull version 1.0.0? It definitely doesn't have the new option:

```
(base) [juan:~]$ mazter --help                                                                                                                                                                                                (padre)
mazter 1.0.0
dystroy <denys.seguret@gmail.com>
Mazes in your terminal - doc at https://dystroy.org/mazter

USAGE:
    mazter [OPTIONS]

OPTIONS:
        --build            don't play, just print a random maze
    -h, --help             Print help information
        --hof              print the Hall of Fame
        --level <LEVEL>    level to play or print - default is the first not won
        --reset            forget all achievements of the user
    -u, --user <USER>      user playing [default: juan]
    -V, --version          Print version information
```

**Comment by Canop** [comment]
It's because it's not officially released.

If you want to test the dev version, you should clone the repo ( `git clone https://github.com/Canop/mazter`) and cd to it.

Then, you may either install it with `cargo install --path .`

Or you may just run it with `cargo run -- --screen-saver`

**Comment by Canop** [comment]
I should also release a version 2.0 in a few days. As you made me look at this project again I had a few ideas that I'm implementing ;)

**Comment by tachijuan** [comment]
That worked. Really like this. Appreciate you doing that.

**Pull request merged**
